**Final Term Exam**

**Alisha Khan - Batch II**

**Section - A**

1) **Text Cleaning with NLTK**

Design a python script to preprocess a raw dataset. Your script must perform tokenize, convert all text to lowercase, remove stopwords, etc. to prepare the data for feature extraction.

In [5]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import string

In [9]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [7]:
# Raw dataset / text
text = "Natural Language Processing is AMAZING! It helps computers understand human language."

In [10]:
# 1. Convert text to lowercase
text = text.lower()

# 2. Tokenization
tokens = word_tokenize(text)

# 3. Remove stopwords and punctuation
stop_words = set(stopwords.words('english'))

cleaned_tokens = []

for word in tokens:
    if word not in stop_words and word not in string.punctuation:
        cleaned_tokens.append(word)

# Final cleaned text
print("Original Tokens:")
print(tokens)

print("\nCleaned Tokens:")
print(cleaned_tokens)

Original Tokens:
['natural', 'language', 'processing', 'is', 'amazing', '!', 'it', 'helps', 'computers', 'understand', 'human', 'language', '.']

Cleaned Tokens:
['natural', 'language', 'processing', 'amazing', 'helps', 'computers', 'understand', 'human', 'language']


2) **Image Data Reduction**

Develop a python function that implement a 2x2 Max pooling operation manuallyusing Numpy. This function should take a feature map as input and return a smaller map that retains the most prominent features.

In [11]:
import numpy as np

In [23]:
# Function for 2x2 Max Pooling
def max_pooling(feature_map):

    rows, cols = feature_map.shape

    # Output size after 2x2 pooling
    pooled_rows = rows // 2
    pooled_cols = cols // 2

    # Create empty pooled feature map
    pooled_map = np.zeros((pooled_rows, pooled_cols))

    # Apply max pooling
    for i in range(0, rows, 2):
        for j in range(0, cols, 2):

            # Select 2x2 region
            region = feature_map[i:i+2, j:j+2]

            # Store maximum value
            pooled_map[i//2, j//2] = np.max(region)

    return pooled_map

In [22]:
# Example Feature Map
feature_map = np.array([
    [1, 3, 2, 4],
    [5, 6, 1, 2],
    [7, 8, 3, 1],
    [2, 4, 9, 5]
])

# Apply Max Pooling
result = max_pooling(feature_map)

# Output
print("Original Feature Map:")
print(feature_map)

print("\nPooled Feature Map:")
print(result)

Original Feature Map:
[[1 3 2 4]
 [5 6 1 2]
 [7 8 3 1]
 [2 4 9 5]]

Pooled Feature Map:
[[6. 4.]
 [8. 9.]]


3) **Lexical Analysis**

Create a python that takes a paragraph of text and applies Part-of-Speech(pos) tagging to every token. The output should clearly identify the grammatical category(e.g, Noun,Verb,Adjective) for each word in the sequence.

In [24]:
import nltk
from nltk.tokenize import word_tokenize

In [25]:
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.


True

In [26]:
# Paragraph text
text = "Artificial Intelligence is transforming the modern world rapidly."

# Tokenization
tokens = word_tokenize(text)

# POS Tagging
pos_tags = nltk.pos_tag(tokens)

# Output
print("Tokens with POS Tags:\n")

for word, tag in pos_tags:
    print(word, " --> ", tag)

Tokens with POS Tags:

Artificial  -->  JJ
Intelligence  -->  NNP
is  -->  VBZ
transforming  -->  VBG
the  -->  DT
modern  -->  JJ
world  -->  NN
rapidly  -->  RB
.  -->  .
