**PYTHON LIBRARIES**

**NUMPY**

A Python library used for performing fast numerical and mathematical operations using arrays.

*1D Numpy in Python*

Create a Python List as follows:

In [ ]:
a = [0, 1, 2, 3, 4]

We can access the data via an index:

In [ ]:
print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


A numpy array is similar to a list. It's usually fixed in size and each element is of the same
type. We can cast a list to a numpy array by first importing numpy:

In [ ]:
import numpy as np

In [ ]:
# we can cast the list
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

As with lists, we can access each element via a square bracket:

In [ ]:
print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


*Type*

If we check the type of the array we get numpy.ndarray:

In [ ]:
type(a)

numpy.ndarray

As numpy arrays contain data of the same type, we can use the attribute "dtype" to
obtain the Data-type of the array’s elements. In this case a 64-bit integer:

In [ ]:
a.dtype

dtype('int64')

We can create a numpy array with real numbers:

In [ ]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])

When we check the type of the array we get numpy.ndarray:

In [ ]:
type(b)

numpy.ndarray

If we examine the attribute dtype we see float 64, as the elements are not integers:

In [ ]:
b.dtype

dtype('float64')

*Assign Value*

We can change the value of the array, consider the array c :

In [ ]:
c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

We can change the first element of the array to 100 as follows:

In [ ]:
c[0] = 100
c

array([100,   1,   2,   3,   4])

We can change the 5th element of the array to 0 as follows:

In [ ]:
c[4] = 400
c

array([100,   1,   2,   3, 400])

*Slicing*

Like lists, we can slice the numpy array, and we can select the elements from 1 to 3 and
assign it to a new numpy array d as follows:

In [ ]:
d = c[1:4]
d

array([1, 2, 3])

We can assign the corresponding indexes to new values as follows:

In [ ]:
# Set the third element and fourth element to 300 and 400
c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

*Assign Value with List*

Similarly, we can use a list to select a specific index. The list ' select ' contains several
values:

In [ ]:
select = [0, 2, 3]

We can use the list as an argument in the brackets. The output is the elements
corresponding to the particular index:

0 -------- 2 -- 3

[100, 1, 2, 300, 400]

In [ ]:
d = c[select]
d

array([100,   2, 300])

We can assign the specified elements to a new value. For example, we can assign the
values to 100 000 as follows:

In [ ]:
c[select] = 100000
c

array([100000,      1, 100000, 100000,    400])

*Other Attributes*

Let's review some basic array attributes using the array a :

In [ ]:
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

The attribute size is the number of elements in the array:

In [ ]:
a.size

5

The next two attributes will make more sense when we get to higher dimensions but let's
review them. The attribute ndim represents the number of array dimensions or the rank
of the array, in this case, one:

In [ ]:
a.ndim

1

The attribute shape is a tuple of integers indicating the size of the array in each
dimension:

In [ ]:
a.shape

(5,)

In [ ]:
mean = a.mean()
mean

np.float64(2.0)

In [ ]:
standard_deviation=a.std()
standard_deviation

np.float64(1.4142135623730951)

In [ ]:
max = a.max()
max

np.int64(4)

In [ ]:
min = a.min()
min

np.int64(0)

*Numpy Array Operations*

*Array Addition*

Consider the numpy array u :

In [ ]:
u = np.array([1, 0])
u

array([1, 0])

Consider the numpy array v :

In [ ]:
v = np.array([0, 1])
v

array([0, 1])

We can add the two arrays and assign it to z:

In [ ]:
z = u + v
z

array([1, 1])

*Array Multiplication*

Consider the vector numpy array y :

In [ ]:
y = np.array([1, 2])
y

array([1, 2])

We can multiply every element in the array by 2:

In [ ]:
z = 2 * y
z

array([2, 4])

This is equivalent to multiplying a vector by a scaler:

*Product of Two Numpy Arrays*

Consider the following array u :

In [ ]:
u = np.array([1, 2])
u

array([1, 2])

Consider the following array v :

In [ ]:
v = np.array([3, 2])
v

array([3, 2])

The product of the two numpy arrays u and v is given by:

In [ ]:
z = u * v
z

array([3, 4])

*Dot Product*

The dot product of the two numpy arrays u and v is given by:

In [ ]:
np.dot(u, v) # product then sum

np.int64(7)

*Adding Constant to a Numpy Array*

Consider the following array:

In [ ]:
u = np.array([1, 2, 3, -1])
u

array([ 1,  2,  3, -1])

Adding the constant 1 to each element in the array:

In [ ]:
u + 1

array([2, 3, 4, 0])

*Mathematical Functions*

We can access the value of pie in numpy as follows :

In [ ]:
np.pi

3.141592653589793

We can create the following numpy array in Radians:

In [ ]:
x = np.array([0, np.pi/2 , np.pi])

We can apply the function sin to the array x and assign the values to the array y ;
this applies the sine function to each element in the array:

In [ ]:
y = np.sin(x)
y

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

*Linspace*

A useful function for plotting mathematical functions is "linespace". Linespace returns
evenly spaced numbers over a specified interval. We specify the starting point of the
sequence and the ending point of the sequence. The parameter "num" indicates the
Number of samples to generate, in this case 5:

In [ ]:
# Makeup a numpy array within [-2, 2] and 5 elements
np.linspace(-2, 2, num=5) # start, stop, number of values

array([-2., -1.,  0.,  1.,  2.])

If we change the parameter num to 9, we get 9 evenly spaced numbers over the interval
from -2 to 2:

In [ ]:
np.linspace(-2, 2, num=9)

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ])

We can use the function line space to generate 100 evenly spaced samples from the
interval 0 to 2π:

In [ ]:
# Makeup a numpy array within [0, 2π] and 5 elements
x = np.linspace(0, 2*np.pi, num=5)
x

array([0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531])

We can apply the sine function to each element in the array x and assign it to the array
y :

In [ ]:
y = np.sin(x)
y

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16])

*Quiz on 1D Numpy Array*

Implement the following vector subtraction in numpy: u-v

In [ ]:
# Write your code below and press Shift+Enter to execute
u = np.array([1, 0])
v = np.array([0, 1])
u - v

array([ 1, -1])

Multiply the numpy array z with -2:

In [ ]:
# Write your code below and execute
z = np.array([2, 4])

In [ ]:
-2 * z

array([-4, -8])

Consider the list [1, 2, 3, 4, 5] and [1, 0, 1, 0, 1] , and cast both lists to a
numpy array then multiply them together:

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 0, 1, 0, 1])
a * b

array([1, 0, 3, 0, 5])

Convert the list [-1, 1] and [1, 1] to numpy arrays a and b . Find the dot
product:

In [ ]:
a = np.array([-1, 1])
b = np.array([1, 1])
print("The dot product is", np.dot(a,b))

The dot product is 0


Convert the list [1, 0] and [0, 1] to numpy arrays a and b . Find the dot
product:

In [ ]:
a = np.array([1, 0])
b = np.array([0, 1])
print("The dot product is", np.dot(a, b))

The dot product is 0


Convert the list [1, 1] and [0, 1] to numpy arrays a and b . Find the dot
product:

In [ ]:
a = np.array([1, 1])
b = np.array([0, 1])
print("The dot product is", np.dot(a, b))

The dot product is 1


Why are the results of the dot product for [-1, 1] and [1, 1] and the dot product
for [1, 0] and [0, 1] zero, but not zero for the dot product for [1, 1] and [0, 1] ?

The vectors used for question 4 and 5 are perpendicular. As a result, the dot product is zero.