**1D vs 2D**

1D = list jaisa

2D = table jaisa (rows + columns)

*Usage*

1D = simple values store karne ke liye, marks list, prices list

2D = datasets, excel sheets, pandas dataframe, ML model input

*Create a 2D Numpy Array*

In [ ]:
import numpy as np

Consider the list a , the list contains three nested lists each of equal size.

In [ ]:
# Create a list
Lst2 = [[11, 12, 13],
[21, 22, 23],
[31, 32, 33]]
Lst2

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

*Convert list to Numpy Array*

Every element is the same type

In [ ]:
Ar = np.array(Lst2)
Ar

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

*Show the numpy array dimensions*

We can use the attribute ndim to obtain the number of axes or dimensions referred to as the
rank.

In [ ]:
Ar.ndim

2

*Show the numpy array shape*

Attribute shape returns a tuple corresponding to the size or number of each dimension.

In [ ]:
Ar.shape

(3, 3)

*Show the numpy array size*

The total number of elements in the array is given by the attribute size .

In [ ]:
Ar.size

9

*Accessing different elements of a Numpy Array*

We can use rectangular brackets to access the different elements of the array. The
correspondence between the rectangular brackets and the list and the rectangular representation
is shown in the following figure for a 3x3 array:

[A[0,0] A[0,1] A[0,2]

 A[1,0] A[1,1] A[1,2]

 A[2,0] A[2,1] A[2,2]]

*Access the element*

We simply use the square brackets and the indices corresponding to the element we would like:

[11 12 13

 21 22 23

 31 32 33]

In [ ]:
Ar[1, 2] # [row, column]

np.int64(23)

We can also use the following notation to obtain the elements:

In [ ]:
# Access the element on the first row and first column
Ar[0][0] # [row][column]

np.int64(11)

We can also use slicing in numpy arrays. Consider the following figure. We would like to obtain
the first two columns in the first row

In [ ]:
# Access the element on the 1st row and 1st and 2nd columns
Ar[0][0:2] # [row][start:stop+1]

array([11, 12])

Similarly, we can obtain the 2nd and 3rd rows of the 3rd column as follows:

In [ ]:
# Access the element on the 2nd and 3rd rows and 3rd column
Ar[1:3, 2] # [start:stop+1][column]

array([23, 33])

*Basic Operations*

We can also add arrays. The process is identical to matrix addition. Matrix addition of X and Y
is shown in the following figure:

In [ ]:
# Create a numpy array X and Y
X = np.array([[1, 0],
              [0, 1]])
print("X =")
print(X)

Y =np.array([[2,1],
             [1,2]])
print("Y =")
print(Y)


X =
[[1 0]
 [0 1]]
Y =
[[2 1]
 [1 2]]


We can add numpy arrays as follow

In [ ]:
# add X and Y
Z = X + Y
Z

array([[3, 1],
       [1, 3]])

Multiplying a numpy array by a scaler is identical to multiplying a matrix by a scaler. If we multiply the matrix Y by the scaler 2, we simply multiply every element in the matrix by 2 as shown in the figure.

In [ ]:
# create a numpy array Y
Y = np.array([[2,1],
              [1,2]])
Y

array([[2, 1],
       [1, 2]])

In [ ]:
# multiply Y with 2
Z = Y * 2
Z

array([[4, 2],
       [2, 4]])

Multiplication of two arrays corresponds to an element-wise product or Hadamard product. Consider matrix X and Y. The Hadamard product correspond to multiplying each of the elements in the same position, i.e multiplying element contained in the same color boxes together. The result is a new matrix that is the same size as matrix Y or X.

In [ ]:
# create a numpy array Y
Y = np.array([[2,1],
              [1,2]])
Y

array([[2, 1],
       [1, 2]])

In [ ]:
# create a numpy array X
X = np.array([[1,0],
              [0,1]])
X

array([[1, 0],
       [0, 1]])

In [ ]:
# multiply X * Y
Z = X * Y
Z

array([[2, 0],
       [0, 2]])

We can also perform the matrix multiplication as follow

In [ ]:
# Create a matrix A
A = np.array([[0, 1, 1],
[1, 0, 1]]) # 2 x 3 Matix
A

array([[0, 1, 1],
       [1, 0, 1]])

In [ ]:
# Create a matrix B
B = np.array([[1, 1],
[1, 1],
[-1, 1]]) # 3 x 2 Matrix
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

We use the numpy function dot to multiply the arrays together.

In [ ]:
# Calculate the dot product
Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

We use the numpy attribute T to calculate the transposed matrix

In [ ]:
# Create a matrix C
C = np.array([[1,1],
[2,2],
[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [ ]:
# Get the transposed of C
C.T

array([[1, 2, 3],
       [1, 2, 3]])